const {
  PROVIDER_STATUSES,
  UI_PROVIDER_VERIFICATION_STATUSES,
} = require('./enums');

function toUiProviderVerificationStatus(status) {
  switch (status) {
    case PROVIDER_STATUSES.PENDING_REVIEW:
      return UI_PROVIDER_VERIFICATION_STATUSES.PENDING;
    case PROVIDER_STATUSES.APPROVED:
      return UI_PROVIDER_VERIFICATION_STATUSES.APPROVED;
    case PROVIDER_STATUSES.REJECTED:
      return UI_PROVIDER_VERIFICATION_STATUSES.REJECTED;
    case PROVIDER_STATUSES.SUSPENDED:
      return UI_PROVIDER_VERIFICATION_STATUSES.SUSPENDED;
    case PROVIDER_STATUSES.PRE_REGISTERED:
    default:
      return UI_PROVIDER_VERIFICATION_STATUSES.DRAFT;
  }
}

function fromUiProviderVerificationStatus(status) {
  switch (status) {
    case UI_PROVIDER_VERIFICATION_STATUSES.PENDING:
      return PROVIDER_STATUSES.PENDING_REVIEW;
    case UI_PROVIDER_VERIFICATION_STATUSES.APPROVED:
      return PROVIDER_STATUSES.APPROVED;
    case UI_PROVIDER_VERIFICATION_STATUSES.REJECTED:
      return PROVIDER_STATUSES.REJECTED;
    case UI_PROVIDER_VERIFICATION_STATUSES.SUSPENDED:
      return PROVIDER_STATUSES.SUSPENDED;
    case UI_PROVIDER_VERIFICATION_STATUSES.DRAFT:
    default:
      return PROVIDER_STATUSES.PRE_REGISTERED;
  }
}

module.exports = {
  fromUiProviderVerificationStatus,
  toUiProviderVerificationStatus,
};
