import { StyleSheet } from "react-native";
import { Colors, Fonts, CommonStyles, Spacing, Radius } from "../../../../constant/styles";
import { authTheme } from "../../auth/theme/authTheme";

function alpha(hex, opacity) {
    const sanitized = hex.replace('#', '').trim();
    const normalized = sanitized.length === 3
        ? sanitized
            .split('')
            .map((character) => `${character}${character}`)
            .join('')
        : sanitized;

    const r = parseInt(normalized.slice(0, 2), 16);
    const g = parseInt(normalized.slice(2, 4), 16);
    const b = parseInt(normalized.slice(4, 6), 16);

    return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export const DiscoverySpacing = Spacing;
export const DiscoveryRadius = Radius;

export const DiscoveryTypography = {
    heroEyebrow: {
        ...Fonts.whiteColor12Medium,
        color: 'rgba(255,255,255,0.76)',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
    },
    heroTitle: {
        ...Fonts.whiteColor24Bold,
        fontSize: 28,
        lineHeight: 34,
    },
    heroBody: {
        ...Fonts.whiteColor13Medium,
        color: 'rgba(255,255,255,0.78)',
        lineHeight: 20,
    },
    screenTitle: {
        ...Fonts.blackColor24Bold,
        fontSize: 24,
        lineHeight: 30,
    },
    sectionTitle: {
        ...Fonts.blackColor18Bold,
        fontSize: 18,
        lineHeight: 24,
    },
    sectionAction: {
        ...Fonts.primaryColor14Medium,
        color: Colors.discoveryAccentColor,
    },
    body: {
        ...Fonts.blackColor14Medium,
        color: Colors.blackColor,
        lineHeight: 20,
    },
    bodyMuted: {
        ...Fonts.grayColor14Medium,
        color: Colors.discoveryMutedColor,
        lineHeight: 20,
    },
    caption: {
        ...Fonts.grayColor12Medium,
        color: Colors.discoverySubtleTextColor,
        lineHeight: 18,
    },
    chip: {
        ...Fonts.primaryColor14Medium,
        color: Colors.discoveryAccentColor,
    },
};

export const DiscoveryPrimitives = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: Colors.discoveryBackgroundColor,
    },
    headerSurface: {
        backgroundColor: Colors.discoveryDarkColor,
        borderBottomLeftRadius: Radius.xl,
        borderBottomRightRadius: Radius.xl,
        paddingHorizontal: Spacing.xl,
        paddingTop: Spacing.sm,
        paddingBottom: Spacing.xl,
    },
    heroSurface: {
        backgroundColor: Colors.discoveryDarkColor,
        borderRadius: Radius.xl,
        padding: Spacing.xl,
        ...CommonStyles.cardShadow,
    },
    contentSurface: {
        backgroundColor: Colors.whiteColor,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        ...CommonStyles.softShadow,
    },
    elevatedSurface: {
        backgroundColor: Colors.whiteColor,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        ...CommonStyles.cardShadow,
    },
    tintedSurface: {
        backgroundColor: Colors.discoveryCardTintColor,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.25)',
        ...CommonStyles.cardShadow,
    },
    primaryButton: {
        backgroundColor: Colors.discoveryAccentColor,
        minHeight: 52,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        ...CommonStyles.softShadow,
    },
    secondaryButton: {
        backgroundColor: Colors.discoverySoftSurfaceColor,
        minHeight: 52,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
    },
    inputSurface: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        minHeight: 56,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        ...CommonStyles.softShadow,
    },
    searchSurface: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        minHeight: 58,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        ...CommonStyles.cardShadow,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    chip: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: Radius.pill,
        backgroundColor: Colors.discoveryChipBackgroundColor,
    },
    badge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: Radius.pill,
        backgroundColor: Colors.discoveryWarmColor,
    },
    tabPill: {
        minHeight: 42,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.discoverySoftSurfaceColor,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
    },
    tabPillActive: {
        backgroundColor: Colors.discoveryAccentColor,
        borderColor: Colors.discoveryAccentColor,
    },
    statPill: {
        flex: 1,
        backgroundColor: Colors.discoverySoftSurfaceColor,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.md,
    },
    listItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.md,
        ...CommonStyles.softShadow,
    },
    iconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: 'rgba(255,255,255,0.12)',
    },
    softIconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: Colors.discoverySoftSurfaceColor,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: Spacing.xl,
        paddingVertical: Spacing.xxl,
        backgroundColor: Colors.whiteColor,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.discoveryBorderColor,
    },
});

export const AinevoieDiscoverySpacing = Spacing;
export const AinevoieDiscoveryRadius = Radius;

export const AinevoieDiscoveryTokens = {
    accent: authTheme.brand.primary,
    accentSoft: authTheme.brand.primarySoft,
    accentPressed: authTheme.button.primaryBackgroundPressed,
    accentShadow: alpha(authTheme.brand.primary, 0.26),
    accentDark: authTheme.brand.primaryDark,
    brandDark: authTheme.text.primary,
    surfaceAccent: alpha(authTheme.brand.primary, 0.1),
    surfaceAccentStrong: alpha(authTheme.brand.primary, 0.18),
    appBackground: authTheme.auth.background,
    sectionBackground: '#FCFBFF',
    surfaceCard: authTheme.auth.surface,
    surfaceInput: authTheme.auth.inputBackground,
    surfaceSubtle: '#F3F1FA',
    surfaceSoft: alpha(authTheme.brand.primary, 0.08),
    surfaceMuted: '#F8F7FC',
    textPrimary: authTheme.text.primary,
    textSecondary: authTheme.text.secondary,
    textMuted: authTheme.text.muted,
    textOnImage: authTheme.text.onDark,
    textOnImageMuted: authTheme.text.onDarkMuted,
    borderSubtle: authTheme.border.subtle,
    borderAccentSoft: alpha(authTheme.brand.primary, 0.16),
    borderFocus: authTheme.auth.inputBorderFocused,
    error: authTheme.error.default,
    rating: '#F2AA3B',
    handle: '#D7DCE8',
    overlaySoft: alpha(authTheme.brand.primary, 0.05),
    imageOverlay: 'rgba(15, 18, 31, 0.24)',
    sheetBackdrop: 'rgba(15, 18, 31, 0.32)',
    snackBackground: '#222631',
    iconNeutral: '#A6ADBB',
    tabBarBackground: authTheme.auth.surface,
    tabBarBorder: authTheme.border.subtle,
    statusBarBackground: authTheme.auth.background,
};

export const AinevoieDiscoveryTypography = {
    heroEyebrow: {
        ...Fonts.grayColor12Bold,
        color: authTheme.text.secondary,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    heroTitle: {
        ...Fonts.blackColor24Bold,
        color: authTheme.text.primary,
        fontSize: 32,
        lineHeight: 40,
    },
    heroBody: {
        ...Fonts.blackColor14Medium,
        color: authTheme.text.secondary,
        lineHeight: 22,
    },
    heroEyebrowOnImage: {
        ...Fonts.whiteColor12Medium,
        color: authTheme.text.onDarkMuted,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    heroTitleOnImage: {
        ...Fonts.whiteColor24Bold,
        color: authTheme.text.onDark,
        fontSize: 30,
        lineHeight: 38,
    },
    heroBodyOnImage: {
        ...Fonts.whiteColor14Medium,
        color: authTheme.text.onDarkMuted,
        lineHeight: 22,
    },
    screenTitle: {
        ...Fonts.blackColor24Bold,
        color: authTheme.text.primary,
        fontSize: 26,
        lineHeight: 32,
    },
    sectionTitle: {
        ...Fonts.blackColor18Bold,
        color: authTheme.text.primary,
        fontSize: 18,
        lineHeight: 24,
    },
    sectionAction: {
        ...Fonts.blackColor14Bold,
        color: authTheme.link.default,
    },
    body: {
        ...Fonts.blackColor14Medium,
        color: authTheme.text.primary,
        lineHeight: 20,
    },
    bodyMuted: {
        ...Fonts.grayColor14Medium,
        color: authTheme.text.secondary,
        lineHeight: 20,
    },
    caption: {
        ...Fonts.grayColor12Medium,
        color: authTheme.text.muted,
        lineHeight: 18,
    },
    chip: {
        ...Fonts.blackColor14Bold,
        color: authTheme.brand.primaryDark,
    },
};

export const AinevoieDiscoveryPrimitives = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: AinevoieDiscoveryTokens.appBackground,
    },
    headerSurface: {
        paddingHorizontal: Spacing.xl,
        paddingTop: Spacing.sm,
        paddingBottom: Spacing.xl,
        backgroundColor: 'transparent',
    },
    heroSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.xl,
        padding: Spacing.xl,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        ...CommonStyles.softShadow,
    },
    softHeroSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.xl,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.lg,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        shadowColor: '#141923',
        shadowOpacity: 0.04,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
        elevation: 3,
    },
    contentSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        ...CommonStyles.softShadow,
    },
    featureSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderAccentSoft,
        shadowColor: AinevoieDiscoveryTokens.accentShadow,
        shadowOpacity: 0.08,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
        elevation: 4,
    },
    elevatedSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        ...CommonStyles.cardShadow,
    },
    tintedSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceSoft,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: alpha(authTheme.brand.primary, 0.12),
    },
    primaryButton: {
        backgroundColor: AinevoieDiscoveryTokens.accent,
        minHeight: 56,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: AinevoieDiscoveryTokens.accent,
        shadowOpacity: 0.24,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
        elevation: 5,
    },
    secondaryButton: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        minHeight: 52,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
    inputSurface: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: AinevoieDiscoveryTokens.surfaceInput,
        minHeight: 58,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.lg,
        borderWidth: 1.5,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        shadowColor: '#141923',
        shadowOpacity: 0.03,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 1,
    },
    searchSurface: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        minHeight: 62,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.lg,
        borderWidth: 1.5,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        ...CommonStyles.softShadow,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    chip: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: Radius.pill,
        backgroundColor: AinevoieDiscoveryTokens.accentSoft,
    },
    quietChip: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: Radius.pill,
        backgroundColor: AinevoieDiscoveryTokens.surfaceSubtle,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
    badge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: Radius.pill,
        backgroundColor: alpha(authTheme.brand.primary, 0.18),
    },
    iconBadge: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: AinevoieDiscoveryTokens.surfaceSoft,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderAccentSoft,
    },
    tabPill: {
        minHeight: 42,
        paddingHorizontal: Spacing.lg,
        borderRadius: Radius.pill,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: AinevoieDiscoveryTokens.surfaceSubtle,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
    tabPillActive: {
        backgroundColor: AinevoieDiscoveryTokens.accent,
        borderColor: AinevoieDiscoveryTokens.accent,
    },
    statPill: {
        flex: 1,
        backgroundColor: AinevoieDiscoveryTokens.surfaceSubtle,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.md,
    },
    listItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.md,
        ...CommonStyles.softShadow,
    },
    iconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
    softIconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: AinevoieDiscoveryTokens.surfaceSubtle,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
    sheetSurface: {
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderTopLeftRadius: Radius.xl,
        borderTopRightRadius: Radius.xl,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
        ...CommonStyles.cardShadow,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: Spacing.xl,
        paddingVertical: Spacing.xxl,
        backgroundColor: AinevoieDiscoveryTokens.surfaceCard,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: AinevoieDiscoveryTokens.borderSubtle,
    },
});

export const AinevoieDiscoveryTabBar = {
    shell: {
        height: 64,
        backgroundColor: AinevoieDiscoveryTokens.tabBarBackground,
        paddingTop: Spacing.xs,
        paddingBottom: Spacing.sm,
        borderTopWidth: 1,
        borderTopColor: AinevoieDiscoveryTokens.tabBarBorder,
        shadowColor: '#141923',
        shadowOpacity: 0.06,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: -2 },
        elevation: 10,
    },
    activeIconColor: AinevoieDiscoveryTokens.accent,
    inactiveIconColor: AinevoieDiscoveryTokens.iconNeutral,
};
